### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by schrej-zz** [georgringer/news_importicsxml#26]
Error handler (BE): PHP Runtime Deprecation Notice: Array and string offset access syntax with curly braces is deprecated in /homepages/11/d582349469/htdocs/tsv-zirndorf/htdocs/typo3conf/ext/news_importicsxml/Resources/Private/Contrib/picoFeed/lib/PicoFeed/Client/Url.php line 144

Curly braces have to be replaced by brackets []

**Comment by tkowtsch** [comment]
Issue is fixed for a while with https://github.com/georgringer/news_importicsxml/commit/3d85c3763e2a7ee27b48d848f302626b17520a6c
