### ISSUE TITLE
Extension ignores already existing slugs

### ISSUE THREAD

**Issue by schrej-zz** [georgringer/news_importicsxml#40]
When there already exists a title (Slug) with the same name, the extension does not change the slug to a unique slug (e.g. "tilte-1").
Instead the links the other news artikel is shown.

**Comment by georgringer** [comment]
Don't really understand the issue. Can you describe with which records are already, which are imported, what happens and what do you expect? Thanks

**Comment by schrej-zz** [comment]
Hi @georgringer,
i have a news article from quite awhile with the title "Stadtmeisterschaften im Laufen".
The slug of this news article is "stadtmeisterschaften-im-laufen".
I now imported an RSS feed via news_importxml with another news with se same title ("Stadtmeisterschaften im Laufen").
The extesion now generates exactly the same slug (stadtmeisterschaften-im-laufen).
In the frontend the newly imported rss news article now directs to the old news article insted of the imported one.
When I manually add a news article with an identical title, the slug is automatically extended by a number (e.g. stadtmeisterschaften-im-laufen-1). This is, what I would have expected also via the rss import.

**Comment by georgringer** [comment]
thanks for the report, fixed
