### ISSUE TITLE
New slugs created on every import

### ISSUE THREAD

**Issue by m-strotmeier** [georgringer/news_importicsxml#41]
I am using TYPO3 11.5.22, news 10.0.3 and the dev-master of news_importicsxml.
In the current version (maybe after the new slug generation was introduced in issue https://github.com/georgringer/news_importicsxml/issues/40), I noticed that the import generates new slugs on every RSS import. 

Example: I have a message with title "Test", on first import the slug "_test_" is generated correctly. On the next import of the same item, the slug changes to "_test-1_", on the very next to "_test_" and so on. 

Already existing slugs should not be changed, am I right?

**Comment by olemo** [comment]
Did you find a solution for this issue?

**Comment by georgringer** [comment]
maybe because of the slug configuration? haven't checked yet tbh

**Comment by georgringer** [comment]
solved with latest commit, however requires latest dev version of ext:news as well

**Comment by olemo** [comment]
Thanks a lot - great relieve! But: The dependencies are broken now. Required news in composer.json is
"georgringer/news": "^11.1.3",
which doesn't exist...

**Comment by georgringer** [comment]
you can have `"georgringer/news":"dev-main as 11.1.3"`

**Comment by olemo** [comment]
Ah. Didn't know that this works. Thank you. 

I think, there is another bug: The class ImportJob constructor is missing the $configuration parameter. It should be sth. like this I guess:
 ```

/**
     * ImportJob constructor.
     * @param TaskConfiguration $configuration
     * @param XmlMapper $xmlMapper
     * @param IcsMapper $icsMapper
     * @param NewsImportService $newsImportService
     */
    public function __construct(
        TaskConfiguration $configuration,
        XmlMapper $xmlMapper,
        IcsMapper $icsMapper,
        NewsImportService $newsImportService
    ) {
        $this->logger = GeneralUtility::makeInstance(LogManager::class)->getLogger(__CLASS__);
        $this->xmlMapper = $xmlMapper;
        $this->icsMapper = $icsMapper;
        $this->newsImportService = $newsImportService;
        $this->configuration = $configuration;
    }

```

**Comment by georgringer** [comment]
IMO not as is set by a different method
```
$importJob = new ImportJob($xmlMapper, $icsMapper, $newsImportService);
$importJob->setConfiguration($this->createConfiguration($input));
 ```

**Comment by olemo** [comment]
I see. But the ImportTask still uses ObjectManager

**Comment by georgringer** [comment]
true, but now not anymore - removed it ;)

**Comment by olemo** [comment]
Very, very nice! Great thanks for your support!!
