### ISSUE TITLE
Scheduler command: mapping parameters expect separation by LF

### ISSUE THREAD

**Issue by tkowtsch** [georgringer/news_importicsxml#44]
Splitting up the mapping parameters is done using LF as delimiter.

`GeneralUtility::trimExplode(LF, $this->mapping, true);`

Creating the scheduler command through TYPO3s backend does not support this - the form is rendered as single line input that clears off any kind of line feeds. 

Suggestion: Add support for another delimiter, e.g. double slash ("//").

**Comment by georgringer** [comment]
wanna do a PR?, i gues ssomething like a `|` is better

**Comment by nebrot** [comment]
For us it only works if we **delete** this line too: https://github.com/georgringer/news_importicsxml/blob/3ae977e6bf806a0e4db1f22512c06a20d59d6ce9/Classes/Command/ImportCommand.php#L77

Example Mapping: `1:Testone|2:Testtwo|3:Testthree|4:Testfour`
