### ISSUE TITLE
Manual Section "Extending the import" is outdated

### ISSUE THREAD

**Issue by tkowtsch** [georgringer/news_importicsxml#46]
The manual still refers to the old event invocation style with signals/slots. This is deprecated now for a while.
Since TYPO3 v10, Event Dispatching is based on PSR-14.

Suggestion:
- remove old sample code
- Mention that there are PSR-14 based events + link to TYPO3 documentation (https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Events/EventDispatcher/Index.html)
- Link to `ext:news` Event Reference table (https://docs.typo3.org/p/georgringer/news/10.0/en-us/Reference/Events/Index.html#referenceevents)
- Drop a note that an example for the `NewsImportPostHydrateEvent` EventListener is available in `ext:eventnews` 

That's IMHO enough info for starters, but still holds valuable details without duplicating everything.

**Comment by georgringer** [comment]
wanna do a PR?
