### ISSUE TITLE
ICAL Import does not take care of timezone

### ISSUE THREAD

**Issue by tkowtsch** [georgringer/news_importicsxml#47]
Importing ICAL files does not take timezone into account correctly.

According to the ical standard, this is to be handled as UTC timezone ([https://www.kanzaki.com/docs/ical/dtstamp.html](https://www.kanzaki.com/docs/ical/dtstamp.html)) 

`DTSTART:20240623T083000Z`

Converting this into a timestamp should then end up as `1719131400`

But instead, it's stored as `1719124200` which means that all imported timestamps are wrong if you're not running the entire system in UTC (which happes rather seldom, I guess :-) )

**Comment by tkowtsch** [comment]
Issue is known in the used 3rd party library.

Easiest fix could be to add a `date_default_timezone_set('UTC');` in Ical.php

```
        // Unix timestamps after 03:14:07 UTC 2038-01-19 might cause an overflow
        // if 32 bit integers are used.
        date_default_timezone_set('UTC');
        
        $timestamp = mktime((int)$date[4], (int)$date[5], (int)$date[6], (int)$date[2], (int)$date[3], (int)$date[1]);
        return $timestamp;
```

**Comment by georgringer** [comment]
wanna provide a PR?
