### ISSUE TITLE
task not available in scheduler

### ISSUE THREAD

**Issue by zzzooorrrx** [georgringer/news_importicsxml#5]
The mentioned task is not available in scheduler module. Installed from Ter, deinstalled, installed again doesn't help. Any idea?

Typo3 7.6.18
news 6.0.0
eventnews 2.0.1
news_importicsxml 2.0.0

**Comment by georgringer** [comment]
use latest master version

**Comment by zzzooorrrx** [comment]
thx. it's working now.
